TEX_EQUATION_DELIMITER = [
    ["\\begin{equation}", "\\end{equation}"],
    ["\\begin{equation*}", "\\end{equation*}"],
    ["\\begin{align}", "\\end{align}"],
    ["\\begin{align*}", "\\end{align*}"],
    ["\\begin{multline}", "\\end{multline}"],
    ["\\begin{multline*}", "\\end{multline*}"],
    ["\\begin{gather}", "\\end{gather}"],
    ["\\begin{gather*}", "\\end{gather*}"],
    ["\\begin{flalign}", "\\end{flalign}"],
    ["\\begin{flalign*}", "\\end{flalign*}"],
    ["\\begin{alignat}", "\\end{alignat}"],
    ["\\begin{alignat*}", "\\end{alignat*}"],
    ["\\begin{aligneq}", "\\end{aligneq}"],
    ["\\begin{aligneq*}", "\\end{aligneq*}"],
    ["\\begin{subequations}", "\\end{subequations}"],
    ["\\begin{subequations*}", "\\end{subequations*}"],
    ["\\begin{subeqnarray}", "\\end{subeqnarray}"],
    ["\\begin{subeqnarray*}", "\\end{subeqnarray*}"],
    ["\\begin{math}", "\\end{math}"],
    ["\\begin{displaymath}", "\\end{displaymath}"],
    ["\\begin{equation}", "\\end{equation}"],
    ["\\begin{equation*}", "\\end{equation*}"],
    ["\\begin{align}", "\\end{align}"],
    ["\\begin{align*}", "\\end{align*}"],
    ["\\begin{multline}", "\\end{multline}"],
    ["\\begin{multline*}", "\\end{multline*}"],
    ["\\begin{gather}", "\\end{gather}"],
    ["\\begin{gather*}", "\\end{gather*}"],
    ["\\begin{flalign}", "\\end{flalign}"],
    ["\\begin{flalign*}", "\\end{flalign*}"],
    ["\\begin{alignat}", "\\end{alignat}"],
    ["\\begin{alignat*}", "\\end{alignat*}"],
    ["\\begin{aligneq}", "\\end{aligneq}"],
    ["\\begin{aligneq*}", "\\end{aligneq*}"],
    ["\\begin{subequations}", "\\end{subequations}"],
    ["\\begin{subequations*}", "\\end{subequations*}"],
    ["\\begin{subeqnarray}", "\\end{subeqnarray}"],
    ["\\begin{subeqnarray*}", "\\end{subeqnarray*}"],
    ["\\begin{math}", "\\end{math}"],
    ["\\begin{displaymath}", "\\end{displaymath}"],
]


TEX_BEGIN = r"""\documentclass{article}\usepackage{amsmath,amssymb,amsfonts}\usepackage{graphicx}\usepackage{graphicx}\usepackage{amsmath}\usepackage{xcolor}\usepackage{algorithm}\usepackage{algpseudocode}\usepackage{stfloats}\begin{document}"""

TEX_END = r"""\end{document}"""
